##Exercice1 - Bloc 1

###Q1.Importation de Pandas et Verification de la version

In [88]:
import pandas as pd

print('Pandas version :', pd.__version__)

Pandas version : 2.2.2

###Q2.Création d'une série simple

In [89]:
notes = pd.Series([15.50, 12, 18],
    index= ['Ndeye Penda SARR', 'Ousmane DIALLO', 'Moussa DIABY']
)
print(notes)

Ndeye Penda SARR    15.5
Ousmane DIALLO      12.0
Moussa DIABY        18.0
dtype: float64

###Q3.Création d'un dataframe

In [90]:
data = {
          "Nom": ["SARR", "DIALLO", "DIABY", "DJIGO", "DIALLO"],
          "Prenom": ["Ndeye Penda","Ousmane", "Moussa", "Abdou", "Mariama"],
          "Classe": ["DEV-DATA","DEV-DATA","DEV-DATA","DEV-DATA","DEV-DATA"],
          "Ville": ["Mbour","Parcelles Assainies","Guediawaye","Medina","Yoff"]
      }

df = pd.DataFrame(data)
df.dtypes

Nom       object
Prenom    object
Classe    object
Ville     object
dtype: object

###Q4.Affichage des premières lignes du dataframe

In [91]:
df.head()

      Nom       Prenom    Classe                Ville
0    SARR  Ndeye Penda  DEV-DATA                Mbour
1  DIALLO      Ousmane  DEV-DATA  Parcelles Assainies
2   DIABY       Moussa  DEV-DATA           Guediawaye
3   DJIGO        Abdou  DEV-DATA               Medina
4  DIALLO      Mariama  DEV-DATA                 Yoff

###Q5.Affichage des colonnes dataframe

In [92]:
print(df.columns)

Index(['Nom', 'Prenom', 'Classe', 'Ville'], dtype='object')

###Q6.Affichage du nombre de lignes et de colonnes

In [93]:
print(df.shape)

(5, 4)

##Exercice 2 - Bloc 2

###Q1 Chargement d'un fichier CSV

In [94]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving promotion_p8.csv to promotion_p8 (1).csv

In [95]:
apprenant = pd.read_csv('promotion_p8.csv')

###Q2. Affichage des premières lignes

In [96]:
apprenant.head()

,Nom,Age,Filiere,Note_Python,Note_SQL,Note_ML,Statut,Ville
0,Ndeye Penda Sarr,23.0,Dev Data,16.5,15.0,17.0,Admis,Dakar
1,Alassane Ndour,24.0,dev data,18.0,17.0,NaN,admis,Dakar
2,Fatou Diallo,22.0,DEV DATA,14.0,13.5,12.0,ADMIS,Thiès
3,Moussa Diop,25.0,Dev Data,15.5,NaN,14.0,Admis,Saint-Louis
4,Aminata Fall,23.0,Dev Web,13.0,12.0,11.5,Non Admis,Dakar

###Q3. Affichage des informations du dataset

In [97]:
apprenant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nom          19 non-null     object
 1   Age          19 non-null     float64
 2   Filiere      20 non-null     object
 3   Note_Python  19 non-null     float64
 4   Note_SQL     19 non-null     float64
 5   Note_ML      18 non-null     float64
 6   Statut       20 non-null     object
 7   Ville        20 non-null     object
dtypes: float64(4), object(4)
memory usage: 1.4+ KB

###Q4. Affichage des statistiques descriptives

In [98]:
apprenant.describe()

             Age  Note_Python   Note_SQL    Note_ML
count  19.000000    19.000000  19.000000  18.000000
mean   23.473684    15.157895  14.184211  13.694444
std     1.218762     2.279453   2.168016   2.941283
min    22.000000    11.000000  10.500000   9.500000
25%    22.500000    13.750000  12.750000  11.625000
50%    23.000000    15.000000  14.000000  13.250000
75%    24.000000    16.750000  15.750000  16.125000
max    26.000000    19.000000  18.000000  19.500000

###Q5. Identification des colonnes numériques

In [99]:
numeric_cols = apprenant.select_dtypes(include=["number"]).columns
print(numeric_cols)

Index(['Age', 'Note_Python', 'Note_SQL', 'Note_ML'], dtype='object')

###Q6. Recherche des valeurs manquantes

In [100]:
apprenant.isna().sum()

Nom            1
Age            1
Filiere        0
Note_Python    1
Note_SQL       1
Note_ML        2
Statut         0
Ville          0
dtype: int64

## Exercice 3 - Bloc 3

###Q1 Affichage d'une colonne

In [101]:
select_colonne= apprenant['Ville']
print(select_colonne)
print(type(select_colonne))

0           Dakar
1           Dakar
2           Thiès
3     Saint-Louis
4           Dakar
5      Ziguinchor
6           Dakar
7           Thiès
8           Dakar
9     Saint-Louis
10          Thiès
11          Dakar
12          Dakar
13          Thiès
14          Dakar
15     Ziguinchor
16          Dakar
17    Saint-Louis
18          Dakar
19          Dakar
Name: Ville, dtype: object
<class 'pandas.core.series.Series'>

###Q2 - Affichage de plusieurs colonnes

In [102]:
select_plus_col= apprenant[['Nom', 'Age', 'Statut', 'Ville']]
print(select_plus_col)
print(type(select_plus_col))

                 Nom   Age     Statut        Ville
0   Ndeye Penda Sarr  23.0      Admis        Dakar
1     Alassane Ndour  24.0      admis        Dakar
2       Fatou Diallo  22.0      ADMIS        Thiès
3        Moussa Diop  25.0      Admis  Saint-Louis
4       Aminata Fall  23.0  Non Admis        Dakar
5       Ibrahima Sow  26.0      Admis   Ziguinchor
6      Mariama Balde  22.0  Non Admis        Dakar
7        Cheikh Wade  24.0      Admis        Thiès
8      Rokhaya Gueye  23.0  Non Admis        Dakar
9         Ousmane Ba  25.0      Admis  Saint-Louis
10      Fatou Diallo  22.0      ADMIS        Thiès
11   Aissatou Ndiaye  24.0      Admis        Dakar
12        Modou Faye  23.0  Non Admis        Dakar
13               NaN  22.0      Admis        Thiès
14       Khady Mbaye   NaN  Non Admis        Dakar
15   Souleymane Diop  24.0      Admis   Ziguinchor
16         Adja Seck  23.0  Non admis        Dakar
17        Pape Thiaw  25.0      Admis  Saint-Louis
18        Ndèye Fall  22.0  Non Admis        Dakar
19      Binta Camara  24.0      Admis        Dakar
<class 'pandas.core.frame.DataFrame'>

###Q3 - Filtrage des étudiants ayant plus de 20 ans

In [103]:
masque = apprenant['Age']>20

print(masque)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14    False
15     True
16     True
17     True
18     True
19     True
Name: Age, dtype: bool

In [104]:
filtre_age= apprenant[masque]
print(filtre_age)

                 Nom   Age   Filiere  Note_Python  Note_SQL  Note_ML  \
0   Ndeye Penda Sarr  23.0  Dev Data         16.5      15.0     17.0
1     Alassane Ndour  24.0  dev data         18.0      17.0      NaN
2       Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
3        Moussa Diop  25.0  Dev Data         15.5       NaN     14.0
4       Aminata Fall  23.0   Dev Web         13.0      12.0     11.5
5       Ibrahima Sow  26.0  Dev Data         17.5      16.0     18.0
6      Mariama Balde  22.0   Dev Web          NaN      14.5     13.0
7        Cheikh Wade  24.0  Dev Data         16.0      15.5     15.0
8      Rokhaya Gueye  23.0   Dev Web         12.5      11.5     10.0
9         Ousmane Ba  25.0  Dev Data         19.0      18.0     19.5
10      Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
11   Aissatou Ndiaye  24.0   dev web         15.0      14.0      NaN
12        Modou Faye  23.0  Dev Data         13.5      12.5     11.0
13               NaN  22.0  Dev Data         14.5      13.0     13.5
15   Souleymane Diop  24.0  Dev Data         18.5      17.5     17.0
16         Adja Seck  23.0   dev web         12.0      11.0     10.5
17        Pape Thiaw  25.0  Dev Data         17.0      16.0     16.5
18        Ndèye Fall  22.0   Dev Web         14.0      13.5     12.0
19      Binta Camara  24.0  Dev Data         16.5      15.0     14.5

       Statut        Ville
0       Admis        Dakar
1       admis        Dakar
2       ADMIS        Thiès
3       Admis  Saint-Louis
4   Non Admis        Dakar
5       Admis   Ziguinchor
6   Non Admis        Dakar
7       Admis        Thiès
8   Non Admis        Dakar
9       Admis  Saint-Louis
10      ADMIS        Thiès
11      Admis        Dakar
12  Non Admis        Dakar
13      Admis        Thiès
15      Admis   Ziguinchor
16  Non admis        Dakar
17      Admis  Saint-Louis
18  Non Admis        Dakar
19      Admis        Dakar

###Q4 - Filtrage des notes supérieures à 15

In [105]:
masque_note = apprenant['Note_Python'] > 15
print(masque_note)

0      True
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19     True
Name: Note_Python, dtype: bool

In [106]:
nouveau_df = apprenant[masque_note]
print(nouveau_df)

                 Nom   Age   Filiere  Note_Python  Note_SQL  Note_ML Statut  \
0   Ndeye Penda Sarr  23.0  Dev Data         16.5      15.0     17.0  Admis
1     Alassane Ndour  24.0  dev data         18.0      17.0      NaN  admis
3        Moussa Diop  25.0  Dev Data         15.5       NaN     14.0  Admis
5       Ibrahima Sow  26.0  Dev Data         17.5      16.0     18.0  Admis
7        Cheikh Wade  24.0  Dev Data         16.0      15.5     15.0  Admis
9         Ousmane Ba  25.0  Dev Data         19.0      18.0     19.5  Admis
15   Souleymane Diop  24.0  Dev Data         18.5      17.5     17.0  Admis
17        Pape Thiaw  25.0  Dev Data         17.0      16.0     16.5  Admis
19      Binta Camara  24.0  Dev Data         16.5      15.0     14.5  Admis

          Ville
0         Dakar
1         Dakar
3   Saint-Louis
5    Ziguinchor
7         Thiès
9   Saint-Louis
15   Ziguinchor
17  Saint-Louis
19        Dakar

###Q5 - Tri des données par âge

In [107]:
tri_age_defaut = apprenant.sort_values('Age')
print(tri_age_defaut)

                 Nom   Age   Filiere  Note_Python  Note_SQL  Note_ML  \
2       Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
6      Mariama Balde  22.0   Dev Web          NaN      14.5     13.0
13               NaN  22.0  Dev Data         14.5      13.0     13.5
10      Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
18        Ndèye Fall  22.0   Dev Web         14.0      13.5     12.0
8      Rokhaya Gueye  23.0   Dev Web         12.5      11.5     10.0
4       Aminata Fall  23.0   Dev Web         13.0      12.0     11.5
12        Modou Faye  23.0  Dev Data         13.5      12.5     11.0
16         Adja Seck  23.0   dev web         12.0      11.0     10.5
0   Ndeye Penda Sarr  23.0  Dev Data         16.5      15.0     17.0
1     Alassane Ndour  24.0  dev data         18.0      17.0      NaN
11   Aissatou Ndiaye  24.0   dev web         15.0      14.0      NaN
15   Souleymane Diop  24.0  Dev Data         18.5      17.5     17.0
7        Cheikh Wade  24.0  Dev Data         16.0      15.5     15.0
19      Binta Camara  24.0  Dev Data         16.5      15.0     14.5
3        Moussa Diop  25.0  Dev Data         15.5       NaN     14.0
17        Pape Thiaw  25.0  Dev Data         17.0      16.0     16.5
9         Ousmane Ba  25.0  Dev Data         19.0      18.0     19.5
5       Ibrahima Sow  26.0  Dev Data         17.5      16.0     18.0
14       Khady Mbaye   NaN   Dev Web         11.0      10.5      9.5

       Statut        Ville
2       ADMIS        Thiès
6   Non Admis        Dakar
13      Admis        Thiès
10      ADMIS        Thiès
18  Non Admis        Dakar
8   Non Admis        Dakar
4   Non Admis        Dakar
12  Non Admis        Dakar
16  Non admis        Dakar
0       Admis        Dakar
1       admis        Dakar
11      Admis        Dakar
15      Admis   Ziguinchor
7       Admis        Thiès
19      Admis        Dakar
3       Admis  Saint-Louis
17      Admis  Saint-Louis
9       Admis  Saint-Louis
5       Admis   Ziguinchor
14  Non Admis        Dakar

###Q6 - Tri des notes par ordre décroissant

In [108]:
tri_note_desc = apprenant.sort_values('Note_Python' , ascending = False)
print(tri_note_desc)

                 Nom   Age   Filiere  Note_Python  Note_SQL  Note_ML  \
9         Ousmane Ba  25.0  Dev Data         19.0      18.0     19.5
15   Souleymane Diop  24.0  Dev Data         18.5      17.5     17.0
1     Alassane Ndour  24.0  dev data         18.0      17.0      NaN
5       Ibrahima Sow  26.0  Dev Data         17.5      16.0     18.0
17        Pape Thiaw  25.0  Dev Data         17.0      16.0     16.5
19      Binta Camara  24.0  Dev Data         16.5      15.0     14.5
0   Ndeye Penda Sarr  23.0  Dev Data         16.5      15.0     17.0
7        Cheikh Wade  24.0  Dev Data         16.0      15.5     15.0
3        Moussa Diop  25.0  Dev Data         15.5       NaN     14.0
11   Aissatou Ndiaye  24.0   dev web         15.0      14.0      NaN
13               NaN  22.0  Dev Data         14.5      13.0     13.5
2       Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
18        Ndèye Fall  22.0   Dev Web         14.0      13.5     12.0
10      Fatou Diallo  22.0  DEV DATA         14.0      13.5     12.0
12        Modou Faye  23.0  Dev Data         13.5      12.5     11.0
4       Aminata Fall  23.0   Dev Web         13.0      12.0     11.5
8      Rokhaya Gueye  23.0   Dev Web         12.5      11.5     10.0
16         Adja Seck  23.0   dev web         12.0      11.0     10.5
14       Khady Mbaye   NaN   Dev Web         11.0      10.5      9.5
6      Mariama Balde  22.0   Dev Web          NaN      14.5     13.0

       Statut        Ville
9       Admis  Saint-Louis
15      Admis   Ziguinchor
1       admis        Dakar
5       Admis   Ziguinchor
17      Admis  Saint-Louis
19      Admis        Dakar
0       Admis        Dakar
7       Admis        Thiès
3       Admis  Saint-Louis
11      Admis        Dakar
13      Admis        Thiès
2       ADMIS        Thiès
18  Non Admis        Dakar
10      ADMIS        Thiès
12  Non Admis        Dakar
4   Non Admis        Dakar
8   Non Admis        Dakar
16  Non admis        Dakar
14  Non Admis        Dakar
6   Non Admis        Dakar

##Exercice 4 - Bloc 4

###Q1 Recherche des valeurs manquantes

In [109]:
apprenant.isnull()

      Nom    Age  Filiere  Note_Python  Note_SQL  Note_ML  Statut  Ville
0   False  False    False        False     False    False   False  False
1   False  False    False        False     False     True   False  False
2   False  False    False        False     False    False   False  False
3   False  False    False        False      True    False   False  False
4   False  False    False        False     False    False   False  False
5   False  False    False        False     False    False   False  False
6   False  False    False         True     False    False   False  False
7   False  False    False        False     False    False   False  False
8   False  False    False        False     False    False   False  False
9   False  False    False        False     False    False   False  False
10  False  False    False        False     False    False   False  False
11  False  False    False        False     False     True   False  False
12  False  False    False        False     False    False   False  False
13   True  False    False        False     False    False   False  False
14  False   True    False        False     False    False   False  False
15  False  False    False        False     False    False   False  False
16  False  False    False        False     False    False   False  False
17  False  False    False        False     False    False   False  False
18  False  False    False        False     False    False   False  False
19  False  False    False        False     False    False   False  False

###Q2 - Remplacement des valeurs nulles

In [110]:
apprenant['Note_Python'] = apprenant['Note_Python'].fillna(apprenant['Note_Python'].mean())
apprenant['Note_SQL']    = apprenant['Note_SQL'].fillna(apprenant['Note_SQL'].mean())
apprenant['Note_ML']     = apprenant['Note_ML'].fillna(apprenant['Note_ML'].mean())

apprenant['Age'] = apprenant['Age'].fillna(apprenant['Age'].median())

apprenant = apprenant.dropna(subset=['Nom'])

###Q3 - Suppression des doublons

In [111]:
print(f'Avant : {len(apprenant)} lignes')
apprenant = apprenant.drop_duplicates()
print(f'Après : {len(apprenant)} lignes')

Avant : 19 lignes
Après : 18 lignes

###Q4 - Renommage de colonnes

In [112]:
apprenant.dtypes

Nom             object
Age            float64
Filiere         object
Note_Python    float64
Note_SQL       float64
Note_ML        float64
Statut          object
Ville           object
dtype: object

In [113]:
apprenant.rename(columns={'Nom': 'Nom Complet'}).head()

,Nom Complet,Age,Filiere,Note_Python,Note_SQL,Note_ML,Statut,Ville
0,Ndeye Penda Sarr,23.0,Dev Data,16.5,15.000000,17.000000,Admis,Dakar
1,Alassane Ndour,24.0,dev data,18.0,17.000000,13.694444,admis,Dakar
2,Fatou Diallo,22.0,DEV DATA,14.0,13.500000,12.000000,ADMIS,Thiès
3,Moussa Diop,25.0,Dev Data,15.5,14.184211,14.000000,Admis,Saint-Louis
4,Aminata Fall,23.0,Dev Web,13.0,12.000000,11.500000,Non Admis,Dakar

###Q5- Convertion d'une colonne en entier

In [114]:
apprenant['Age'] = apprenant['Age'].astype(int)
apprenant['Age'].dtypes

dtype('int64')

###Q6- Nettoyage du dataset

In [115]:
# Normaliser Filiere et Statut
apprenant['Filiere'] = apprenant['Filiere'].str.strip().str.title()
# 'dev data' → 'Dev Data', 'DEV DATA' → 'Dev Data'

apprenant['Statut'] = apprenant['Statut'].str.strip().str.title()
# 'admis' → 'Admis', 'ADMIS' → 'Admis', 'Non admis' → 'Non Admis'

print(apprenant['Filiere'].unique())
print(apprenant['Statut'].unique())

['Dev Data' 'Dev Web']
['Admis' 'Non Admis']

##Exercice 5 - Bloc 5

###Q1- Calcul de la moyenne des notes de python

In [116]:
moyenne = apprenant['Note_Python'].mean()
print(f'Moyenne Python : {moyenne:.2f}/20')

Moyenne Python : 15.26/20

###Q2- Trouver la valeur maximale

In [117]:
max_note = apprenant['Note_Python'].max()
meilleur = apprenant[apprenant['Note_Python'] == max_note]['Nom'].values[0]
print(f'Meilleure note Python : {max_note} — {meilleur}')

Meilleure note Python : 19.0 — Ousmane Ba

###Q3- Compte des catégories

In [118]:
# Répartition par filière
print(apprenant['Filiere'].value_counts())

# Répartition admis / non admis
print(apprenant['Statut'].value_counts())

Filiere
Dev Data    11
Dev Web      7
Name: count, dtype: int64
Statut
Admis        11
Non Admis     7
Name: count, dtype: int64

###Q4- Moyenne par groupe avec groupby()

In [119]:
print(apprenant.groupby('Filiere')['Note_Python'].mean().round(2))

Filiere
Dev Data    16.55
Dev Web     13.24
Name: Note_Python, dtype: float64

###Q5- Compte du nombre d'éléments par catégorie

In [120]:
print(apprenant.groupby('Filiere')['Nom'].count())

Filiere
Dev Data    11
Dev Web      7
Name: Nom, dtype: int64

###Q6 - Statistiques simples — tableau de bord de la promo

In [121]:
print('=== TABLEAU DE BORD PROMOTION P8 ===')
print(f"Effectif total   : {len(apprenant)}")
print(f"Taux d'admission : {(apprenant['Statut']=='Admis').mean()*100:.1f}%")
print(f"Moy. Python      : {apprenant['Note_Python'].mean():.2f}")
print(f"Moy. SQL         : {apprenant['Note_SQL'].mean():.2f}")
print(f"Moy. ML          : {apprenant['Note_ML'].mean():.2f}")
print(f"Meilleur étudiant: {apprenant.loc[apprenant['Note_Python'].idxmax(), 'Nom']}")

=== TABLEAU DE BORD PROMOTION P8 ===
Effectif total   : 18
Taux d'admission : 61.1%
Moy. Python      : 15.26
Moy. SQL         : 14.29
Moy. ML          : 13.80
Meilleur étudiant: Ousmane Ba

##Exercice 6 - Bloc 6

###Q1- Concaténation de deux DataFrames

In [123]:
# Deux groupes de la promotion
groupe1 = apprenant.iloc[:9].copy()
groupe2 = apprenant.iloc[9:].copy()

# Table des informations complémentaires (ville, contact)
apprenant_villes = pd.DataFrame({
    'Nom': ['Ndeye Penda Sarr','Alassane Ndour','Ousmane Ba'],
    'Email': ['np@email.sn','alou@email.sn','ousba@email.sn'],
    'Telephone': ['771234567','782345678','763456789']
})

In [124]:
promo_complete = pd.concat([groupe1, groupe2], ignore_index=True)
print(f'Groupe1 : {len(groupe1)} lignes')
print(f'Groupe2 : {len(groupe2)} lignes')
print(f'Total   : {len(promo_complete)} lignes')

Groupe1 : 9 lignes
Groupe2 : 9 lignes
Total   : 18 lignes

###Q2- Fusion de deux tables simples

In [125]:
apprenant_villes = pd.DataFrame({
    'Nom': ['Ndeye Penda Sarr', 'Alassane Ndour', 'Ousmane Ba'],
    'Email': ['np@email.sn', 'alou@email.sn', 'ousba@email.sn'],
    'Telephone': ['771234567', '782345678', '763456789']
})

apprenant_enrichi = pd.merge(apprenant, apprenant_villes, on='Nom', how='left')
print(apprenant_enrichi[['Nom', 'Email', 'Telephone']].head(3))

                Nom          Email  Telephone
0  Ndeye Penda Sarr    np@email.sn  771234567
1    Alassane Ndour  alou@email.sn  782345678
2      Fatou Diallo            NaN        NaN

###Q3- Affichage des données communes

In [126]:
apprenant_commun = pd.merge(apprenant, apprenant_villes, on='Nom', how='inner')
print(apprenant_commun[['Nom','Email']])

                Nom           Email
0  Ndeye Penda Sarr     np@email.sn
1    Alassane Ndour   alou@email.sn
2        Ousmane Ba  ousba@email.sn

###Q4- Ajout d'une nouvelle colonne calculée

In [127]:
apprenant['Moyenne'] = apprenant[['Note_Python','Note_SQL','Note_ML']].mean(axis=1).round(2)
print(apprenant[['Nom','Note_Python','Note_SQL','Note_ML','Moyenne']].head(5))

                Nom  Note_Python   Note_SQL    Note_ML  Moyenne
0  Ndeye Penda Sarr         16.5  15.000000  17.000000    16.17
1    Alassane Ndour         18.0  17.000000  13.694444    16.23
2      Fatou Diallo         14.0  13.500000  12.000000    13.17
3       Moussa Diop         15.5  14.184211  14.000000    14.56
4      Aminata Fall         13.0  12.000000  11.500000    12.17

##Exercice 7 - Bloc 7

###Q1- Connection de Pandas à une base de données SQLite

In [128]:
import sqlite3
import pandas as pd

# Créer/ouvrir la base de données
conn = sqlite3.connect('p8_devdata.db')
print('Connexion établie !')

Connexion établie !

###Q2- Lecture d'une table SQL dans un DataFrame

In [129]:
apprenant.to_sql('apprenants', conn, if_exists='replace', index=False)

# Puis on le relit depuis SQL
apprenant_sql = pd.read_sql('SELECT * FROM apprenants', conn)
print(apprenant_sql.head())

                Nom  Age   Filiere  Note_Python   Note_SQL    Note_ML  \
0  Ndeye Penda Sarr   23  Dev Data         16.5  15.000000  17.000000
1    Alassane Ndour   24  Dev Data         18.0  17.000000  13.694444
2      Fatou Diallo   22  Dev Data         14.0  13.500000  12.000000
3       Moussa Diop   25  Dev Data         15.5  14.184211  14.000000
4      Aminata Fall   23   Dev Web         13.0  12.000000  11.500000

      Statut        Ville  Moyenne
0      Admis        Dakar    16.17
1      Admis        Dakar    16.23
2      Admis        Thiès    13.17
3      Admis  Saint-Louis    14.56
4  Non Admis        Dakar    12.17

###Q3- Affichage des données recupérées

In [130]:
print(f'Lignes lues depuis SQL : {len(apprenant_sql)}')
print(apprenant_sql.dtypes)

Lignes lues depuis SQL : 18
Nom             object
Age              int64
Filiere         object
Note_Python    float64
Note_SQL       float64
Note_ML        float64
Statut          object
Ville           object
Moyenne        float64
dtype: object

###Q4- Filtrage des données avec pandas après lecture

In [131]:
# Option 1 : filtrer directement dans la requête SQL
admis_sql = pd.read_sql(
    "SELECT * FROM apprenants WHERE Statut = 'Admis'",
    conn
)

# Option 2 : lire tout puis filtrer avec Pandas
admis_pd = apprenant_sql[apprenant_sql['Statut'] == 'Admis']

print(f'Admis (SQL)    : {len(admis_sql)}')
print(f'Admis (Pandas) : {len(admis_pd)}')

Admis (SQL)    : 11
Admis (Pandas) : 11

###Q5- Sauvegarde d'un dataframe dans une base de données

In [132]:
# Créer un résumé par filière et le sauvegarder
resume = apprenant.groupby('Filiere').agg(
    Effectif=('Nom','count'),
    Moy_Python=('Note_Python','mean'),
    Moy_SQL=('Note_SQL','mean'),
).round(2).reset_index()

resume.to_sql('resume_filieres', conn, if_exists='replace', index=False)
print('Table resume_filieres créée !')

Table resume_filieres créée !

###Q6- Comparaison d'une opération SQL et Pandas

In [133]:
# === SQL ===
requete_sql = '''
    SELECT Filiere,
           COUNT(*) AS Effectif,
           AVG(Note_Python) AS Moy_Python
    FROM apprenants
    GROUP BY Filiere
    ORDER BY Moy_Python DESC
'''
print(pd.read_sql(requete_sql, conn))

# === PANDAS équivalent ===
print(
    apprenant.groupby('Filiere')
      .agg(Effectif=('Nom','count'), Moy_Python=('Note_Python','mean'))
      .round(2)
      .sort_values('Moy_Python', ascending=False)
)

    Filiere  Effectif  Moy_Python
0  Dev Data        11   16.545455
1   Dev Web         7   13.236842
          Effectif  Moy_Python
Filiere
Dev Data        11       16.55
Dev Web          7       13.24